### ISSUE TITLE
use of background-image or src as image 

### ISSUE THREAD

**Issue by wortkotze** [DeuxHuitHuit/algolia-webcrawler#42]
Hi I would like to use a background-image or a src of an <img/> tag as my image that should show up in a source. Is this already possible ? I'm not able to create an CSS selector to get this data as its inside of an attribute on this object? 

Probably some ideas how I could do this?

**Comment by fhamon** [comment]
For the background-image, I don't think it will be possible since it would require parsing the style attribute's value. You can fetch the image tag's src attribute without any problems.

You can simply add an object selector like this rough example I did below.

Hope this helps and let me know if it solves your issue.

```json
"selectors": {
	"title": "title",
	"description": "meta[name=\"description\"]",
	"text": "h1, h2, h3, h4, h5, h6, p, li",
	"image": {
		"key": "image",
		"attributes": "src",
		"selector": "img[src]"
	}
}
```

**Comment by wortkotze** [comment]
thx for the fast reply - works great :)
